### Importing libraries

In [48]:
import pandas as pd
import warnings
from pickle import dump
warnings.filterwarnings('ignore')
from sklearn.linear_model import LogisticRegression
from  sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
from sklearn.model_selection import train_test_split,KFold,GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score ,classification_report,confusion_matrix

### Loading the data

In [2]:
text=pd.read_csv('text.csv',index_col=[0])
text.head()

Review  Rating rating_analysis  \
0  nice hotel expensive parking got good deal sta...       4        Positive   
1  ok nothing special charge diamond member hilto...       2        Negative   
2  nice rooms not 4* experience hotel monaco seat...       3         Neutral   
3  unique, great stay, wonderful time hotel monac...       5        Positive   
4  great stay great stay, went seahawk game aweso...       5        Positive   

                                        clean_review  \
0  nice hotel expensive parking got good deal sta...   
1  ok nothing special charge diamond member hilto...   
2  nice rooms experience hotel monaco seattle goo...   
3  unique great stay wonderful time hotel monaco ...   
4  great stay great stay went seahawk game awesom...   

                                    Lemmitize_review  subjectivity  polarity  \
0  nice hotel expensive parking get good deal sta...      0.678095  0.198804   
1  ok nothing special charge diamond member hilto...      0.539858  0.248550   
2  nice room experience hotel monaco seattle good...      0.591954  0.321429   
3  unique great stay wonderful time hotel monaco ...      0.691228  0.504825   
4  great stay great stay go seahawk game awesome ...      0.637088  0.467308   

  sentiment_polarity  no_of_char  no_of_words  
0           Positive         521           80  
1           Positive        1521          228  
2           Positive        1257          189  
3           Positive         538           83  
4           Positive        1091          172

## Tf-ID Vectorizor

In [3]:
tf=TfidfVectorizer()

In [4]:
x_train_df=tf.fit(text['clean_review'])

In [5]:
x_train=x_train_df.transform(text['clean_review'])

In [6]:
X_train,X_test,y_train,y_test=train_test_split(x_train,text['sentiment_polarity'],random_state=30,test_size=0.3,shuffle=True)

In [7]:
X_train.shape,X_test.shape

((14343, 75052), (6148, 75052))

In [8]:
y_train.shape,y_test.shape

((14343,), (6148,))

In [9]:
# defined a function for accuracy
def Accuracy(y_train,y_train_pred,y_test,y_test_pred):
    print('Train Accuracy\n')
    print(classification_report(y_train,y_train_pred))
    print('\n',confusion_matrix(y_train,y_train_pred))
    print('\n',accuracy_score(y_train,y_train_pred))
    print('*'*100)
    print('Test Accuracy\n')
    print(classification_report(y_test,y_test_pred))
    print('\n',confusion_matrix(y_test,y_test_pred))
    print('\n',accuracy_score(y_test,y_test_pred)) 

## Model Building 

## Decsison tree classifier

In [10]:
model_descision=DecisionTreeClassifier(random_state=0)

In [11]:
model_descision.fit(X_train,y_train)

DecisionTreeClassifier(random_state=0)

In [12]:
train_pred=model_descision.predict(X_train)
test_pred=model_descision.predict(X_test)

In [13]:
descison_tree=Accuracy(train_pred,y_train,test_pred,y_test)
descison_tree

Train Accuracy

              precision    recall  f1-score   support

    Negative       1.00      1.00      1.00       831
     Neutral       1.00      1.00      1.00        16
    Positive       1.00      1.00      1.00     13496

    accuracy                           1.00     14343
   macro avg       1.00      1.00      1.00     14343
weighted avg       1.00      1.00      1.00     14343


 [[  831     0     0]
 [    0    16     0]
 [    0     0 13496]]

 1.0
****************************************************************************************************
Test Accuracy

              precision    recall  f1-score   support

    Negative       0.45      0.43      0.44       318
     Neutral       0.00      0.00      0.00         3
    Positive       0.97      0.97      0.97      5827

    accuracy                           0.94      6148
   macro avg       0.47      0.47      0.47      6148
weighted avg       0.94      0.94      0.94      6148


 [[ 138    0  180]
 [   0    0   

## Logistic Model

In [14]:
log=LogisticRegression()

In [15]:
log.fit(X_train,y_train)

LogisticRegression()

In [16]:
log_train=log.predict(X_train)
log_test=log.predict(X_test)

In [17]:
logistic_model=Accuracy(log_train,y_train,log_test,y_test)
logistic_model

Train Accuracy

              precision    recall  f1-score   support

    Negative       0.59      1.00      0.74       492
     Neutral       0.00      0.00      0.00         0
    Positive       1.00      0.97      0.99     13851

    accuracy                           0.97     14343
   macro avg       0.53      0.66      0.58     14343
weighted avg       0.99      0.97      0.98     14343


 [[  490     0     2]
 [    0     0     0]
 [  341    16 13494]]

 0.9749703688210277
****************************************************************************************************
Test Accuracy

              precision    recall  f1-score   support

    Negative       0.34      0.97      0.50       108
     Neutral       0.00      0.00      0.00         0
    Positive       1.00      0.96      0.98      6040

    accuracy                           0.96      6148
   macro avg       0.45      0.65      0.50      6148
weighted avg       0.99      0.96      0.97      6148


 [[ 105    0    3]

## K-Nearest Algorithm

In [18]:
k=KNeighborsClassifier(n_neighbors=35)

In [19]:
k.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=35)

In [20]:
ktrain_pred=k.predict(X_train)
ktest_pred=k.predict(X_test)

In [21]:
k_near=Accuracy(ktrain_pred,y_train,ktest_pred,y_test)
k_near

Train Accuracy

              precision    recall  f1-score   support

    Negative       0.05      0.95      0.09        40
     Neutral       0.00      0.00      0.00         0
    Positive       1.00      0.94      0.97     14303

    accuracy                           0.94     14343
   macro avg       0.35      0.63      0.35     14343
weighted avg       1.00      0.94      0.97     14343


 [[   38     0     2]
 [    0     0     0]
 [  793    16 13494]]

 0.9434567384787004
****************************************************************************************************
Test Accuracy

              precision    recall  f1-score   support

    Negative       0.06      0.94      0.10        18
     Neutral       0.00      0.00      0.00         0
    Positive       1.00      0.95      0.97      6130

    accuracy                           0.95      6148
   macro avg       0.35      0.63      0.36      6148
weighted avg       1.00      0.95      0.97      6148


 [[  17    0    1]

## Random Forest

In [22]:
random=RandomForestClassifier(max_features=400)

In [23]:
random.fit(X_train,y_train)

RandomForestClassifier(max_features=400)

In [24]:
rf_train=random.predict(X_train)
rf_test=random.predict(X_test)

In [25]:
random_forest=Accuracy(rf_train,y_train,rf_test,y_test)
random_forest

Train Accuracy

              precision    recall  f1-score   support

    Negative       1.00      1.00      1.00       831
     Neutral       1.00      1.00      1.00        16
    Positive       1.00      1.00      1.00     13496

    accuracy                           1.00     14343
   macro avg       1.00      1.00      1.00     14343
weighted avg       1.00      1.00      1.00     14343


 [[  831     0     0]
 [    0    16     0]
 [    0     0 13496]]

 1.0
****************************************************************************************************
Test Accuracy

              precision    recall  f1-score   support

    Negative       0.06      0.91      0.12        22
     Neutral       0.00      0.00      0.00         0
    Positive       1.00      0.95      0.97      6126

    accuracy                           0.95      6148
   macro avg       0.35      0.62      0.37      6148
weighted avg       1.00      0.95      0.97      6148


 [[  20    0    2]
 [   0    0   

## SVM (Support Vector Machine)

In [26]:
svc=SVC()

In [27]:
svc.fit(X_train,y_train)

SVC()

In [28]:
svctrain=svc.predict(X_train)
svctest=svc.predict(X_test)

In [29]:
support_vector_machine=Accuracy(svctrain,y_train,svctest,y_test)
support_vector_machine

Train Accuracy

              precision    recall  f1-score   support

    Negative       0.96      1.00      0.98       799
     Neutral       0.00      0.00      0.00         0
    Positive       1.00      1.00      1.00     13544

    accuracy                           1.00     14343
   macro avg       0.65      0.67      0.66     14343
weighted avg       1.00      1.00      1.00     14343


 [[  799     0     0]
 [    0     0     0]
 [   32    16 13496]]

 0.9966534197866556
****************************************************************************************************
Test Accuracy

              precision    recall  f1-score   support

    Negative       0.22      0.99      0.36        69
     Neutral       0.00      0.00      0.00         0
    Positive       1.00      0.96      0.98      6079

    accuracy                           0.96      6148
   macro avg       0.41      0.65      0.45      6148
weighted avg       0.99      0.96      0.97      6148


 [[  68    0    1]

### Adaboost 

In [30]:
adabosst=AdaBoostClassifier()

In [31]:
adabosst.fit(X_train,y_train)

AdaBoostClassifier()

In [32]:
add_train=adabosst.predict(X_train)
add_test=adabosst.predict(X_test)

In [33]:
Adaboost_model=Accuracy(add_train,y_train,add_test,y_test)
Adaboost_model

Train Accuracy

              precision    recall  f1-score   support

    Negative       0.24      0.68      0.36       298
     Neutral       0.94      1.00      0.97        15
    Positive       0.99      0.96      0.97     14030

    accuracy                           0.95     14343
   macro avg       0.72      0.88      0.77     14343
weighted avg       0.98      0.95      0.96     14343


 [[  202     0    96]
 [    0    15     0]
 [  629     1 13400]]

 0.9493829742731646
****************************************************************************************************
Test Accuracy

              precision    recall  f1-score   support

    Negative       0.26      0.71      0.38       112
     Neutral       0.00      0.00      0.00         1
    Positive       0.99      0.96      0.98      6035

    accuracy                           0.96      6148
   macro avg       0.42      0.56      0.45      6148
weighted avg       0.98      0.96      0.97      6148


 [[  79    0   33]

## Naive bayes

In [34]:
mb=MultinomialNB()

In [35]:
mb.fit(X_train,y_train)

MultinomialNB()

In [36]:
mb_train=adabosst.predict(X_train)
mb_test=adabosst.predict(X_test)

In [37]:
multinomial_model=Accuracy(mb_train,y_train,mb_test,y_test)
multinomial_model

Train Accuracy

              precision    recall  f1-score   support

    Negative       0.24      0.68      0.36       298
     Neutral       0.94      1.00      0.97        15
    Positive       0.99      0.96      0.97     14030

    accuracy                           0.95     14343
   macro avg       0.72      0.88      0.77     14343
weighted avg       0.98      0.95      0.96     14343


 [[  202     0    96]
 [    0    15     0]
 [  629     1 13400]]

 0.9493829742731646
****************************************************************************************************
Test Accuracy

              precision    recall  f1-score   support

    Negative       0.26      0.71      0.38       112
     Neutral       0.00      0.00      0.00         1
    Positive       0.99      0.96      0.98      6035

    accuracy                           0.96      6148
   macro avg       0.42      0.56      0.45      6148
weighted avg       0.98      0.96      0.97      6148


 [[  79    0   33]

### Deployment

In [39]:
# build the intelligence for tfid Vectorizer 
x=text['clean_review']
y=text['sentiment_polarity']

In [52]:
tfid_deploy=TfidfVectorizer()
tfid_deploy=tfid.fit(x)

In [53]:
# converting text into numeric for svm
x_train=tfid_deploy.transform(x)

In [54]:
logistic_model_deploy=LogisticRegression()
logistic_model_deploy.fit(x_train,y)

LogisticRegression()

In [55]:
#saving svm n tfid into pkl
dump(obj=logistic_model_deploy,file=open('logistic_model_deploy.pkl','wb'))
dump(obj=tfid_deploy,file=open('tfid_deploy.pkl','wb'))